### ISSUE TITLE
NullPointerException on hasLocalFieldWithName

### ISSUE THREAD

**Issue by lahnsurfer** [michalborek/mockito-eclipse-tools#12]
I always get a NullPointerException if it trigger the quickfix on a field:

```
java.lang.NullPointerException
    at pl.greenpath.mockito.ide.refactoring.assisst.MocksQuickAssistProcessor.hasLocalFieldWithName(MocksQuickAssistProcessor.java:119)
    at pl.greenpath.mockito.ide.refactoring.assisst.MocksQuickAssistProcessor.isConvertToSpyPossile(MocksQuickAssistProcessor.java:102)
    at pl.greenpath.mockito.ide.refactoring.assisst.MocksQuickAssistProcessor.getAssists(MocksQuickAssistProcessor.java:43)
```

I am using Eclipse 4.3 and pl.greenpath.mockito.ide.refactoring_1.2.0.201403042101.jar

**Comment by michalborek** [comment]
Thanks for the ticket. I'm gonna check it right away.

**Comment by michalborek** [comment]
Ok I see the reason of that. 

This feature is implemented for local variables only and that's why it crashed on field.

I'm gonna fix the NPE and in near future support spy on fields.

**Comment by michalborek** [comment]
Problem is fixed

**Comment by michalborek** [comment]
Tim, the new version 1.3.0 is out, you can use update site to install new version without mentioned NPE.
